# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receta', models.CharField(max_length=50)),
                ('ingredientes', models.TextField()),
                ('preparacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('ingredientes', models.TextField(help_text='Redacta los ingredientes')),
                ('prepacion', models.TextField(verbose_name='Preparación')),
                ('tiempo_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
